
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Negocio
{

using System;
    using System.Collections.Generic;
    
public partial class Controladores
{

    public int Id { get; set; }

    public string Codigo { get; set; }

    public string Descripcion { get; set; }

    public int Numero { get; set; }

    public Nullable<int> UsoLec1 { get; set; }

    public Nullable<int> UsoLec2 { get; set; }

    public Nullable<int> Bloqueado { get; set; }

    public Nullable<int> Consola { get; set; }

    public Nullable<int> Horario { get; set; }

    public string Notas { get; set; }

    public string Firmware { get; set; }

    public Nullable<System.DateTime> Alta { get; set; }

    public Nullable<int> TipoCard { get; set; }

    public string FormatoCard { get; set; }

    public string Puerto { get; set; }

    public string IP_Speed { get; set; }

    public string MACAddr { get; set; }

    public Nullable<int> Liberado { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<int> RegistraProh { get; set; }

    public Nullable<int> EsReloj { get; set; }

    public Nullable<int> VerFoto { get; set; }

    public Nullable<int> APB { get; set; }

    public string IpProtocol { get; set; }

    public Nullable<int> T_Pumoba { get; set; }

    public Nullable<int> T_SensPA { get; set; }

    public Nullable<int> UsoLec3 { get; set; }

    public Nullable<int> UsoLec4 { get; set; }

    public Nullable<int> PredVis { get; set; }

    public Nullable<int> MultiTablas { get; set; }

    public Nullable<int> QtyHabL { get; set; }

    public Nullable<int> QtyHabE { get; set; }

    public Nullable<int> nOpt1 { get; set; }

    public Nullable<int> nOpt2 { get; set; }

    public Nullable<int> nOpt3 { get; set; }

    public Nullable<int> TMEF { get; set; }

    public string CamaraWeb { get; set; }

    public string EspCard { get; set; }

    public Nullable<int> TecFun { get; set; }

    public Nullable<int> HusoHorario { get; set; }

    public string IPPort { get; set; }

    public Nullable<int> Cacheo { get; set; }

    public Nullable<int> Parking { get; set; }

    public Nullable<int> Horario1 { get; set; }

    public Nullable<int> Cliente { get; set; }

    public string TActuHabi { get; set; }

    public string MemLeida { get; set; }

    public Nullable<int> ConnStatus { get; set; }

    public string TxtDisplay { get; set; }

    public string Gateway { get; set; }

    public string MascaraIP { get; set; }

    public string DondeVer { get; set; }

    public Nullable<int> Planta { get; set; }

    public string HabiPtr { get; set; }

    public Nullable<int> UsoTablaH { get; set; }

    public Nullable<System.DateTime> FechaLastComm { get; set; }

    public Nullable<int> THActivas { get; set; }

}

}
