
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Negocio
{

using System;
    using System.Collections.Generic;
    
public partial class Fichadas
{

    public int Id { get; set; }

    public int Controlador { get; set; }

    public string Codigo { get; set; }

    public Nullable<int> Accion { get; set; }

    public Nullable<int> Consola { get; set; }

    public Nullable<int> Tarjeta { get; set; }

    public Nullable<System.DateTime> Capturada { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public Nullable<int> Transferida { get; set; }

    public Nullable<int> TReal { get; set; }

    public Nullable<int> Secuencia { get; set; }

    public string Observaciones { get; set; }

    public Nullable<int> IdPerso { get; set; }

}

}
