
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Negocio
{

using System;
    using System.Collections.Generic;
    
public partial class Personas
{

    public int Id { get; set; }

    public string Apellido { get; set; }

    public string Nombre { get; set; }

    public Nullable<System.DateTime> FechaNacimiento { get; set; }

    public Nullable<int> Cargo { get; set; }

    public Nullable<int> Sector { get; set; }

    public Nullable<int> Seccion { get; set; }

    public Nullable<int> CentroDeCosto { get; set; }

    public Nullable<int> Division1 { get; set; }

    public Nullable<int> Categoria { get; set; }

    public string Notas { get; set; }

    public string Legajo { get; set; }

    public Nullable<int> Tarjeta { get; set; }

    public string Otros { get; set; }

    public Nullable<System.DateTime> Alta { get; set; }

    public Nullable<System.DateTime> Baja { get; set; }

    public string email { get; set; }

    public Nullable<int> Adentro { get; set; }

    public Nullable<int> Nume2 { get; set; }

    public Nullable<int> Horario { get; set; }

    public string Telefono { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<int> Sexo { get; set; }

    public Nullable<int> Modificado { get; set; }

    public Nullable<int> Provisoria { get; set; }

    public Nullable<System.DateTime> LastReg { get; set; }

    public string DesdeCit { get; set; }

    public string HastaCit { get; set; }

    public string Autoriza { get; set; }

    public string ARTVence { get; set; }

    public Nullable<int> VistoPor { get; set; }

    public Nullable<int> Seteos1 { get; set; }

    public Nullable<int> MultiValor { get; set; }

    public Nullable<int> Empresa { get; set; }

    public string DondeVer { get; set; }

    public Nullable<System.DateTime> VenceTarje { get; set; }

    public Nullable<System.DateTime> VenceProvi { get; set; }

    public string LastEntrada { get; set; }

    public Nullable<int> IdPerso { get; set; }

    public string OtroDoc { get; set; }

    public string TNDocumento { get; set; }

    public Nullable<int> Visitado { get; set; }

    public string OtraTarjeta { get; set; }

    public string ZANBE { get; set; }

    public string OtroDP1 { get; set; }

    public string OtroDP2 { get; set; }

}

}
