
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class CtaAplicacionDeConsumos
{

    public long Clave { get; set; }

    public long MovimientoItemClave { get; set; }

    public string ConsumoTipoId { get; set; }

    public string IdentificadorConsumo1 { get; set; }

    public string IdentificadorConsumo2 { get; set; }

    public Nullable<long> MovimientoItemClaveReferencia { get; set; }

    public string UnidadMedidaId { get; set; }

    public decimal Cantidad { get; set; }

    public string Usuario { get; set; }

    public System.DateTime FechaModificacion { get; set; }

    public int Version { get; set; }

}

}
