
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class CtaCierresDePeriodos
{

    public long Clave { get; set; }

    public System.DateTime FechaDesde { get; set; }

    public System.DateTime FechaHasta { get; set; }

    public string Usuario { get; set; }

    public System.DateTime FechaModificacion { get; set; }

    public int Version { get; set; }

    public string Descripcion { get; set; }

}

}
