
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class CtaMovimientos
{

    public CtaMovimientos()
    {

        this.CtaMovimientosAplicacion = new HashSet<CtaMovimientosAplicacion>();

        this.CtaMovimientosCuotas = new HashSet<CtaMovimientosCuotas>();

        this.CtaMovimientosFinancieras = new HashSet<CtaMovimientosFinancieras>();

    }


    public long MovimientoNro { get; set; }

    public string MovimientoTipoId { get; set; }

    public string ComprobanteId { get; set; }

    public int SignoComprobante { get; set; }

    public string CondicionDePagoId { get; set; }

    public int SucursalId { get; set; }

    public string EstablecimientoId { get; set; }

    public int ComprobanteNro { get; set; }

    public System.DateTime FechaMovimiento { get; set; }

    public System.DateTime FechaComprobante { get; set; }

    public Nullable<System.DateTime> FechaVencimientoBaseInformada { get; set; }

    public Nullable<int> EntidadId { get; set; }

    public string EntidadDescripcion { get; set; }

    public string EntidadGrupoId { get; set; }

    public Nullable<int> GaranteId { get; set; }

    public Nullable<int> PatrocinadorId { get; set; }

    public string CuentaContableTipoId { get; set; }

    public string ListaPrecioId { get; set; }

    public string DivisaId { get; set; }

    public decimal Importe { get; set; }

    public string Comentario { get; set; }

    public string Usuario { get; set; }

    public System.DateTime FechaModificacion { get; set; }

    public int Version { get; set; }

    public Nullable<bool> Anulado { get; set; }



    public virtual ICollection<CtaMovimientosAplicacion> CtaMovimientosAplicacion { get; set; }

    public virtual ICollection<CtaMovimientosCuotas> CtaMovimientosCuotas { get; set; }

    public virtual ICollection<CtaMovimientosFinancieras> CtaMovimientosFinancieras { get; set; }

}

}
