
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class CtaMovimientosFinancieras
{

    public long Clave { get; set; }

    public long MovimientoNro { get; set; }

    public int Orden { get; set; }

    public int EntradaSalida { get; set; }

    public string FinancieraPropiaId { get; set; }

    public string ComprobanteId { get; set; }

    public string ComprobanteNro { get; set; }

    public string CuentaContable { get; set; }

    public string CentroDeCosto { get; set; }

    public string DivisaId { get; set; }

    public decimal Importe { get; set; }

    public string Usuario { get; set; }

    public System.DateTime FechaModificacion { get; set; }

    public int Version { get; set; }



    public virtual CtaMovimientos CtaMovimientos { get; set; }

}

}
