
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class CtaMovimientosCuotas
{

    public CtaMovimientosCuotas()
    {

        this.CtaMovimientosAplicacion = new HashSet<CtaMovimientosAplicacion>();

        this.CtaMovimientosAplicacion1 = new HashSet<CtaMovimientosAplicacion>();

    }


    public long Clave { get; set; }

    public long MovimientoNro { get; set; }

    public int Cuota { get; set; }

    public System.DateTime Vencimiento { get; set; }

    public string DivisaId { get; set; }

    public decimal Importe { get; set; }

    public string CuentaCorrienteTipo { get; set; }

    public Nullable<int> origen { get; set; }

    public string Usuario { get; set; }

    public System.DateTime FechaModificacion { get; set; }

    public int Version { get; set; }



    public virtual CtaMovimientos CtaMovimientos { get; set; }

    public virtual ICollection<CtaMovimientosAplicacion> CtaMovimientosAplicacion { get; set; }

    public virtual ICollection<CtaMovimientosAplicacion> CtaMovimientosAplicacion1 { get; set; }

}

}
