
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class uniActas
{

    public long Clave { get; set; }

    public int numeroActa { get; set; }

    public int numeroActaDefinitivo { get; set; }

    public long papel1 { get; set; }

    public long papel2 { get; set; }

    public Nullable<int> ciclo { get; set; }

    public string turno { get; set; }

    public string codmat { get; set; }

    public string libro { get; set; }

    public Nullable<int> folio { get; set; }

    public Nullable<System.DateTime> fecha { get; set; }

    public Nullable<System.DateTime> hora { get; set; }

    public string codins { get; set; }

    public string usrnom { get; set; }

    public Nullable<System.DateTime> ftrn { get; set; }

    public Nullable<int> regional { get; set; }

    public int estadoActa { get; set; }

    public Nullable<int> Fila { get; set; }

    public Nullable<long> MesaId { get; set; }

    public string codigoComprobacion { get; set; }

}

}
