
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class uniAlumnos
{

    public int legprovi { get; set; }

    public Nullable<int> legdef { get; set; }

    public string apellido { get; set; }

    public string nombre { get; set; }

    public Nullable<System.DateTime> fecnac { get; set; }

    public string lugar { get; set; }

    public Nullable<decimal> docnac { get; set; }

    public Nullable<decimal> cedide { get; set; }

    public Nullable<decimal> libciv { get; set; }

    public Nullable<decimal> libenr { get; set; }

    public string sexo { get; set; }

    public string argext { get; set; }

    public string nacion { get; set; }

    public string nropas { get; set; }

    public string tramite { get; set; }

    public string carrera { get; set; }

    public Nullable<int> regional { get; set; }

    public string turno { get; set; }

    public System.DateTime finscrip { get; set; }

    public string email { get; set; }

    public string username { get; set; }

    public Nullable<int> regional_cursa { get; set; }

    public Nullable<int> version2 { get; set; }

    public string documentoExtranjero { get; set; }

    public string PaisDocumento { get; set; }

    public Nullable<int> Origen { get; set; }

    public Nullable<int> IdEntidad { get; set; }

    public Nullable<int> CicloIngreso { get; set; }

    public Nullable<int> CuatriIngreso { get; set; }

    public string Modalidad { get; set; }

    public Nullable<int> IdCanal { get; set; }

    public string CanalDescripcion { get; set; }

    public string Usuario { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

}

}
