
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class UniAniosLectivosFacturados
{

    public int legajo { get; set; }

    public int añoLectivoFacturado { get; set; }

    public Nullable<bool> derechosExamenIncluidos { get; set; }

    public Nullable<bool> PorAnioDeCorte { get; set; }

}

}
