
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class UniAranceles
{

    public long clave { get; set; }

    public int aniolectivo { get; set; }

    public int tipoArancel { get; set; }

    public string condicionDePago { get; set; }

    public string mensajeArancel { get; set; }

    public string usrnom { get; set; }

    public System.DateTime ftrn { get; set; }

    public int fila { get; set; }

    public Nullable<int> tipoOrigen { get; set; }

    public Nullable<long> claveOrigen { get; set; }

}

}
