
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class uniActasAlumnos
{

    public long Clave { get; set; }

    public int legajo { get; set; }

    public string apellido { get; set; }

    public Nullable<int> ausente { get; set; }

    public string cond { get; set; }

    public Nullable<int> notaesc { get; set; }

    public Nullable<int> notaora { get; set; }

    public Nullable<int> notadef { get; set; }

    public int orden { get; set; }

    public Nullable<int> Fila { get; set; }

    public string codigoComprobacion { get; set; }

}

}
