
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class uniCursos
{

    public string codcar { get; set; }

    public int codcur { get; set; }

    public string codmat { get; set; }

    public int ano { get; set; }

    public int cuatri { get; set; }

    public string turno { get; set; }

    public string letrad { get; set; }

    public string letrah { get; set; }

    public string comision { get; set; }

    public Nullable<int> cupo { get; set; }

    public Nullable<int> anotados { get; set; }

    public Nullable<int> anomat { get; set; }

    public string codcur2 { get; set; }

    public string usrnom { get; set; }

    public Nullable<System.DateTime> ftrn { get; set; }

    public Nullable<int> promo { get; set; }

    public Nullable<int> qclases { get; set; }

    public Nullable<int> qparcial { get; set; }

    public Nullable<double> qtopepro { get; set; }

    public Nullable<double> qtopereg { get; set; }

    public Nullable<int> regional { get; set; }

    public Nullable<double> cantprof { get; set; }

    public long id { get; set; }

    public Nullable<int> cupoMinimo { get; set; }

    public int Fila { get; set; }

    public Nullable<int> modalidad { get; set; }

}

}
