
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class uniCorreoEnviado
{

    public int codins { get; set; }

    public int legajoProfesor { get; set; }

    public string cursoid { get; set; }

    public Nullable<System.DateTime> FechaDeEnvio { get; set; }

    public string Emisor { get; set; }

    public string Receptor { get; set; }

    public Nullable<int> EstadoAviso { get; set; }

}

}
