
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class uniCursosDias
{

    public long cursoId { get; set; }

    public int ActividadNro { get; set; }

    public string dia { get; set; }

    public Nullable<int> ActividadTipoId { get; set; }

    public Nullable<System.DateTime> desde { get; set; }

    public Nullable<System.DateTime> hasta { get; set; }

    public Nullable<int> codins { get; set; }

    public Nullable<int> codaul { get; set; }

    public string usrnom { get; set; }

    public Nullable<System.DateTime> ftrn { get; set; }

    public int Version { get; set; }

}

}
