
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class uniInscripcionesMateriasDetalle
{

    public long Clave { get; set; }

    public string codmat { get; set; }

    public Nullable<int> codcur { get; set; }

    public long Fila { get; set; }

    public Nullable<long> cursoId { get; set; }

    public Nullable<System.DateTime> fecha { get; set; }

    public string usuario { get; set; }

}

}
