
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class uniInscripcionesMaterias
{

    public long Clave { get; set; }

    public Nullable<int> legajo { get; set; }

    public Nullable<System.DateTime> finsc { get; set; }

    public Nullable<int> ciclo { get; set; }

    public Nullable<int> cuatri { get; set; }

    public string codcar { get; set; }

    public string Usuario { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public long Fila { get; set; }

    public Nullable<bool> Eliminada { get; set; }

}

}
