
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class uniMatriculaciones
{

    public long Clave { get; set; }

    public int legajoProvisorio { get; set; }

    public int ciclo { get; set; }

    public int tipoMatriculacion { get; set; }

    public string condicionDePago { get; set; }

    public bool Eliminada { get; set; }

    public string mensajeMatri { get; set; }

    public System.DateTime fecha { get; set; }

    public string Usuario { get; set; }

    public int Fila { get; set; }

    public Nullable<long> claveOrigen { get; set; }

    public Nullable<int> anioMaximo { get; set; }

    public Nullable<System.DateTime> fechaModificacion { get; set; }

}

}
