
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class UniProfesoresHs
{

    public long CursoId { get; set; }

    public int ClaseNro { get; set; }

    public int LegajoProfesor { get; set; }

    public Nullable<System.DateTime> Entrada { get; set; }

    public Nullable<System.DateTime> Salida { get; set; }

    public bool Ausente { get; set; }

    public string Usuario { get; set; }

    public bool Revision { get; set; }

    public Nullable<System.DateTime> FechaCursada { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public System.DateTime FechaModificacion { get; set; }

    public int Version { get; set; }

    public bool NoPlanificado { get; set; }

    public Nullable<int> LegajoProfesorReemplazo { get; set; }

    public Nullable<decimal> HsPlanificadas { get; set; }

    public Nullable<decimal> HsEfectivas { get; set; }

    public string Comentarios { get; set; }

    public Nullable<System.DateTime> EntradaEditada { get; set; }

    public Nullable<System.DateTime> SalidaEditada { get; set; }

    public Nullable<int> NovedadesId { get; set; }

    public Nullable<int> Estado { get; set; }

    public Nullable<decimal> HorasAprobadas { get; set; }

}

}
