
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class uniReconocimientoMateriasFirmantes
{

    public int idReconocimientoMaterias { get; set; }

    public int legajo { get; set; }

    public int estado { get; set; }

    public System.DateTime fecha { get; set; }

    public int Fila { get; set; }

    public string CodigoComprobacion { get; set; }

}

}
