
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Security
{

using System;
    using System.Collections.Generic;
    
public partial class uniReconocimientoMaterias
{

    public int Clave { get; set; }

    public Nullable<int> numeroTramite { get; set; }

    public Nullable<int> legajo { get; set; }

    public System.DateTime fecha { get; set; }

    public int estado { get; set; }

    public Nullable<int> numeroResolucion { get; set; }

    public Nullable<System.DateTime> fechaResolucion { get; set; }

    public string usuario { get; set; }

    public Nullable<System.DateTime> fechaModificacion { get; set; }

    public System.DateTime fechaVencimiento { get; set; }

    public Nullable<int> tipoDocumento { get; set; }

    public string nroDocumento { get; set; }

    public string Apellido { get; set; }

    public string Nombre { get; set; }

    public string Contacto { get; set; }

    public int Fila { get; set; }

    public string carrera { get; set; }

    public string CodigoComprobacion { get; set; }

    public long papel1 { get; set; }

    public long papel2 { get; set; }

    public Nullable<bool> baja { get; set; }

    public int Tipo { get; set; }

}

}
