//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumosCapataz {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsumosCapataz.StockMovementServiceSoap")]
    public interface StockMovementServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StockSetStockConsumptionForOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool StockSetStockConsumptionForOrder(ConsumosCapataz.StockMovement FinishedProduct, ConsumosCapataz.StockMovement[] RawMaterials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StockSetStockConsumptionForOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> StockSetStockConsumptionForOrderAsync(ConsumosCapataz.StockMovement FinishedProduct, ConsumosCapataz.StockMovement[] RawMaterials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetStockConsumptionForOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SetStockConsumptionForOrder(int IdCompany, ConsumosCapataz.StockMovement FinishedProduct, ConsumosCapataz.StockMovement[] RawMaterials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetStockConsumptionForOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SetStockConsumptionForOrderAsync(int IdCompany, ConsumosCapataz.StockMovement FinishedProduct, ConsumosCapataz.StockMovement[] RawMaterials);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StockMovement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string batchField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string orderNoField;
        
        private decimal quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
                this.RaisePropertyChanged("Batch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("OrderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockMovementServiceSoapChannel : ConsumosCapataz.StockMovementServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockMovementServiceSoapClient : System.ServiceModel.ClientBase<ConsumosCapataz.StockMovementServiceSoap>, ConsumosCapataz.StockMovementServiceSoap {
        
        public StockMovementServiceSoapClient() {
        }
        
        public StockMovementServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockMovementServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockMovementServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockMovementServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool StockSetStockConsumptionForOrder(ConsumosCapataz.StockMovement FinishedProduct, ConsumosCapataz.StockMovement[] RawMaterials) {
            return base.Channel.StockSetStockConsumptionForOrder(FinishedProduct, RawMaterials);
        }
        
        public System.Threading.Tasks.Task<bool> StockSetStockConsumptionForOrderAsync(ConsumosCapataz.StockMovement FinishedProduct, ConsumosCapataz.StockMovement[] RawMaterials) {
            return base.Channel.StockSetStockConsumptionForOrderAsync(FinishedProduct, RawMaterials);
        }
        
        public bool SetStockConsumptionForOrder(int IdCompany, ConsumosCapataz.StockMovement FinishedProduct, ConsumosCapataz.StockMovement[] RawMaterials) {
            return base.Channel.SetStockConsumptionForOrder(IdCompany, FinishedProduct, RawMaterials);
        }
        
        public System.Threading.Tasks.Task<bool> SetStockConsumptionForOrderAsync(int IdCompany, ConsumosCapataz.StockMovement FinishedProduct, ConsumosCapataz.StockMovement[] RawMaterials) {
            return base.Channel.SetStockConsumptionForOrderAsync(IdCompany, FinishedProduct, RawMaterials);
        }
    }
}
